import { UnifiedNodeConfigPanel } from './common/UnifiedNodeConfigPanel';

export const NODE_CONFIG_PANELS: Record<string, React.FC<any>> = {
    ONEDRIVE: UnifiedNodeConfigPanel,
    GOOGLE_DRIVE: UnifiedNodeConfigPanel,
    GMAIL: UnifiedNodeConfigPanel,
    SCHEDULE: UnifiedNodeConfigPanel,
    OCR: UnifiedNodeConfigPanel,
    ocr: UnifiedNodeConfigPanel,
    IF_ELSE: UnifiedNodeConfigPanel,
    PARSING: UnifiedNodeConfigPanel,
    MONGODB: UnifiedNodeConfigPanel,
    SUMMARIZE: UnifiedNodeConfigPanel,
    SMART_EXTRACTION: UnifiedNodeConfigPanel,
    smart_extraction: UnifiedNodeConfigPanel,
    FILE_UPLOAD: UnifiedNodeConfigPanel,
    file_upload: UnifiedNodeConfigPanel,
    HTTP_REQUEST: UnifiedNodeConfigPanel,
    TESSERACT_OCR: UnifiedNodeConfigPanel,
    SURYA_OCR: UnifiedNodeConfigPanel,
    surya_ocr: UnifiedNodeConfigPanel,
    CODE: UnifiedNodeConfigPanel,
    OUTLOOK: UnifiedNodeConfigPanel,
    RSS: UnifiedNodeConfigPanel,
    AI_AGENT: UnifiedNodeConfigPanel,
    ai_agent: UnifiedNodeConfigPanel,
    GEMINI_MODEL: UnifiedNodeConfigPanel,
    gemini_model: UnifiedNodeConfigPanel,
    GOOGLE_SEARCH_TOOL: UnifiedNodeConfigPanel,
    google_search_tool: UnifiedNodeConfigPanel,
    EMAIL_TEMPLATE: UnifiedNodeConfigPanel,
    email_template: UnifiedNodeConfigPanel,
    BROWSER_SCRAPER: UnifiedNodeConfigPanel,
    browser_scraper: UnifiedNodeConfigPanel,
    DATA_MAPPER: UnifiedNodeConfigPanel,
    data_mapper: UnifiedNodeConfigPanel,
};
