export enum SampleNodeType {
    GOOGLE_DRIVE = 'GOOGLE_DRIVE',
    ONEDRIVE = 'ONEDRIVE',
    GMAIL = 'GMAIL',
    SCHEDULE = 'SCHEDULE',
    OCR = 'OCR',
    IF_ELSE = 'IF_ELSE',
    PARSING = 'PARSING',
    MONGODB = 'MONGODB',
    SUMMARIZE = 'SUMMARIZE',

    SMART_EXTRACTION = 'SMART_EXTRACTION',
    FILE_UPLOAD = 'FILE_UPLOAD',
    HTTP_REQUEST = 'HTTP_REQUEST',
    DATA_MAPPER = 'DATA_MAPPER',
}
// Force recompile
